<?php
/**
 * @file
 * Implements eWAY payments for Drupal Commerce.
 */

 /**
 * Returns an eWAY request URL.
 *
 * @param $payment_method
 * Payment method ID
 *
 * @param $type
 * Type of request e.g. 'endpoint' or 'payment'
 */
function commerce_eway_url($payment_method, $type) {

  // TODO: Get country from payment method settings.
  $country = 'au';
  $method = $payment_method . '_' . $type;

  switch($method) {
  	case 'rapidapi_endpoint':
  		$url = 'https://' . $country . '.ewaypayments.com/hotpotato/soap.asmx?wsdl';
  	break;
  	case 'rapidapi_payment':
  		$url = 'https://' . $country . '.ewaypayments.com/hotpotato/payment';
  	break;
  }

  return $url;
}

/**
 * Submits a SOAP request to an eWay endpoint.
 *
 * @param $payment_method
 *   The payment method instance array associated with this API request.
 * @param $request_method
 *   eWAY request method e.g. CreateAccessCode
 * @param $type
 * Type of request e.g. 'endpoint' or 'payment'
  * @param $mode
 * Transaction mode e.g. 'live' or 'sandbox'
 * @param $request
 *   The request object containing the parameters of the requested services.
 *
 * @return
 *   The response object from the API with properties pertinent to the requested
 *     services.
 */
function commerce_eway_soap_request($payment_method, $request_method, $type, $request) {

	// Get the API endpoint URL for the method's transaction mode.
  $url = commerce_eway_url($payment_method, $type);

  $function = 'commerce_' . 'eway_rapidapi' . '_default_settings';
  $settings = $function();

  // TODO: Log the request.
  if ($payment_method['settings']['log']['request'] == 'request') {
  }

  // Attempt the SOAP request.
  try {
    $soapClient = new SoapClient($url, array());
    switch($request_method) {
    	case 'CreateAccessCode':
    		$response = $soapClient->CreateAccessCode(array('request' => $request));
    	break;
    }
  }
  catch (SoapFault $exception) {
    watchdog('commerce_eway_rapidapi', 'SoapFault: !exception', array('!exception' => '<pre>' . print_r($exception, TRUE) . '</pre>'), WATCHDOG_ERROR);
    return FALSE;
  }

  // Log the response if specified.
  if ($payment_method['settings']['log']['response'] == 'response') {
    watchdog('commerce_eway', 'eWAY RapidAPI response: !param', array('!param' => '<pre>' . check_plain(print_r($response, TRUE)) . '</pre>', WATCHDOG_DEBUG));
  }

  return $response;
}